# Generated by Django 2.2.3 on 2019-07-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190711_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
